### ISSUE TITLE
Symfony Flex

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#12]
**Effort**: high

### Description

Currently, it is difficult to update the production template as you have to fork the repository and manually update the forked repository. With Symfony flex, we are able to provide recipes for our own bundles and provide an easy may to stay up-to-date with the Shopware template files

### Benefits

* Fewer files in the template repository
* Allows easier changes of configurations
* Much easier to update the production template incl. core
* Back to Symfony basics

**Comment by AndreasA** [comment]
Not sure if that should be separate or part of this but I would also like it, if Shopware uses the new symfony/runtime in index.php / console insttetad of using the old version that requires more code, see also the demo project https://github.com/symfony/demo/blob/main/bin/console

**Comment by AndreasA** [comment]
@keulinho  less duplicate code as console and index.php both share a lot of code in common. of course, you could also go the old route from Symfony and use the config/bootstrap.php file.

Otherwise, there is only one more improvement, easier to keep in sync with future Symfony updates as I doubt they will return to the old way. Maybe you could even extend the SymfonyRuntime (https://github.com/symfony/runtime/blob/5.4/SymfonyRuntime.php) and just add your custom parts to the corresponding runtime but otherwise keep the original code - not 100% sure though, would probably need to look into it more.

However, it isn't necessarily needed.

**Comment by JoshuaBehrens** [comment]
I thought we are already going there? https://github.com/shopware/production/pull/107 see last comment about waiting for next release. @jkrzefski you don't have details on that perhaps?

**Comment by AndreasA** [comment]
Ah. Great 😄

**Comment by RafaelKr** [comment]
The Shopware documentation recommends to use a `.env.local.php` files in a production setup for better performance: https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks#.env.local.php

The default Symfony way of creating it is to run `composer dump-env prod` which is only part of symfony/flex - so currently there seems to be no way to create it besides doing it manually.

**Comment by shyim** [comment]
https://www.shopware.com/en/news/shopware-goes-symfony-flex/
