### ISSUE TITLE
Deprecation of the development template

### ISSUE THREAD

**Issue by shyim** [shopware/proposal#21]
**Effort**: low

### Description: 

We have currently two templates to set up Shopware 6. They differ completely in the tooling of bash vs custom script runner written in PHP (psh), which makes it hard for new users to run the correct commands for their shop. 

With this proposal, we deprecate the development template that the users use only the production template

### Benefits

- There is only one way to set up a Shopware shop.
- Less maintenance effort

### Break strategy

- Replace all references in the docs to production template
- Add documentation how to use Docker
- Announce it in a blog post and tweet
- Archive the development repository

**Comment by intheweb** [comment]
All the tooling (PSH and the surrounding scripts) could be an add-on to the production template.

**Comment by AndreasA** [comment]
If the development template is to be deprecated which I think is a good idea because it is completely confusing (having two different templates but for most purposes the production template works perfect), the README in the platform github repository also has to be changed 😄 
https://github.com/shopware/platform#quickstart--installation
