### ISSUE TITLE
"Data has changed? Do you want to save?" alert

### ISSUE THREAD

**Issue by phinpope** [shopware/proposal#32]
**Effort**: low

### Description: 
 If data has been changed/added to a form, a modal that informs the user that they have not yet saved the changes would be great.

### Benefits
Stops users contacting internal tech support with "why aren't my changes showing!"

### Break strategy
Configure in user preferences (default to on)

**Comment by OliverSkroblin** [comment]
Hi @phinpope,
thanks for your idea, however it seems to go more in the direction of a feature instead of a refactoring.

For features please use our [issue tracker](https://issues.shopware.com/?products=SW-6&edition=community,professionalEdition,enterpriseEdition&projects=all&type=1,4&status=open,inProgress,done).

Greetings Oliver
